spring:
    datasource:
        url: jdbc:postgresql://localhost:54320/remindmeof
        username: postgres
        password: Y40gg.Y4gg0.
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 10
    jpa:
        properties:
            hibernate:
                default-schema: SCHEMA_NOTE_SERVICE
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update