#For testing before wiring with eureka server
server:
    port: 0
spring:
    rabbitmq:
        host: localhost
        virtual-host: /
        port: 5672
        username: guest
        password: guest
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/deviceservicedb
        username: postgres
        password: toor
        connection-properties: useUnicode=true;characterEncoding=utf-8
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                temp:
                    use_jdbc_metadata_defaults: false
        open-in-view: false
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411/
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
    instance:
        preferIpAddress: true
management:
    endpoints:
        web:
            exposure:
                include: "*"
    security:
        enabled: false