eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            default-zone: http://localhost:8761/eureka/
server:
    port: ${EUREKA_SERVER_PORT:8761}

spring:
    rabbitmq:
        host: localhost
        virtual-host: /
        port: 5672
        username: guest
        password: guest

management:
    endpoints:
        web:
            exposure:
                include: "*"
    security:
        enabled: false
