server:
    port: 0
spring:
    elasticsearch:
        rest:
            uris: http://127.0.0.1:9200
    data:
        elasticsearch:
            cluster-name: docker-cluster
            cluster-nodes: 127.0.0.1:9300
    rabbitmq:
        host: localhost
        virtual-host: /
        port: 5672
        username: guest
        password: guest
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411/
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
    instance:
        preferIpAddress: true
management:
    endpoints:
        web:
            exposure:
                include: "*"
    security:
        enabled: false